"""empty message

Revision ID: 137d174d4d1a
Revises: 6059ca8cf9ca
Create Date: 2022-05-07 00:49:05.009681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '137d174d4d1a'
down_revision = '6059ca8cf9ca'
branch_labels = None
depends_on = None


def upgrade():
    
    # ### commands auto generated by Alembic - please adjust! ###
    genre = postgresql.ENUM('alternative', 'Blues', 'Classical', 'Country', 'Electronic', 'Folk', 'Funk', 'HipHop', 'HeavyMetal', 'Instrumental', 'Jazz', 'MusicalTheatre', 'Pop', 'Punk', 'RnB', 'Reggae', 'RocknRoll', 'Soul', 'Other', name='genre')
    genre.create(op.get_bind())
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.Enum('alternative', 'Blues', 'Classical', 'Country', 'Electronic', 'Folk', 'Funk', 'HipHop', 'HeavyMetal', 'Instrumental', 'Jazz', 'MusicalTheatre', 'Pop', 'Punk', 'RnB', 'Reggae', 'RocknRoll', 'Soul', 'Other', name='genre')), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    genre = postgresql.ENUM('alternative', 'Blues', 'Classical', 'Country', 'Electronic', 'Folk', 'Funk', 'HipHop', 'HeavyMetal', 'Instrumental', 'Jazz', 'MusicalTheatre', 'Pop', 'Punk', 'RnB', 'Reggae', 'RocknRoll', 'Soul', 'Other', name='genre')
    genre.drop(op.get_bind())
    # ### end Alembic commands ###
