"""empty message

Revision ID: 24784d4e37c2
Revises: 9c906bb51367
Create Date: 2022-05-06 20:53:04.746931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24784d4e37c2'
down_revision = '9c906bb51367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
