"""empty message

Revision ID: 8b3c76de9efb
Revises: 20b437ed85a2
Create Date: 2022-05-06 21:14:09.625130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3c76de9efb'
down_revision = '20b437ed85a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('Show_pkey', 'Show', type_='primary')
    op.create_primary_key('Show_pkey', 'Show', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_pkey', 'Show', type_='primary')
    op.drop_column('Show', 'id')
    op.create_primary_key('Show_pkey', 'Show', ['artist_id', 'venue_id'])
    # ### end Alembic commands ###
