"""empty message

Revision ID: a1e49227162f
Revises: e680d6ec5cac
Create Date: 2022-05-09 01:20:38.034596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e49227162f'
down_revision = 'e680d6ec5cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Show', ['venue_id', 'start_time'])
    op.create_unique_constraint(None, 'Show', ['artist_id', 'start_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='unique')
    op.drop_constraint(None, 'Show', type_='unique')
    # ### end Alembic commands ###
