"""empty message

Revision ID: b1925b5bc66d
Revises: 137d174d4d1a
Create Date: 2022-05-07 01:25:00.089612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1925b5bc66d'
down_revision = '137d174d4d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    genre = postgresql.ENUM('alternative', 'Blues', 'Classical', 'Country', 'Electronic', 'Folk', 'Funk', 'HipHop', 'HeavyMetal', 'Instrumental', 'Jazz', 'MusicalTheatre', 'Pop', 'Punk', 'RnB', 'Reggae', 'RocknRoll', 'Soul', 'Other', name='genre')
    genre.create(op.get_bind())
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.Enum('alternative', 'Blues', 'Classical', 'Country', 'Electronic', 'Folk', 'Funk', 'HipHop', 'HeavyMetal', 'Instrumental', 'Jazz', 'MusicalTheatre', 'Pop', 'Punk', 'RnB', 'Reggae', 'RocknRoll', 'Soul', 'Other', name='genre')), nullable=True))
    op.drop_column('Artist', 'state')
    op.drop_column('Venue', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('Artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('Artist', 'genres')
    genre = postgresql.ENUM('alternative', 'Blues', 'Classical', 'Country', 'Electronic', 'Folk', 'Funk', 'HipHop', 'HeavyMetal', 'Instrumental', 'Jazz', 'MusicalTheatre', 'Pop', 'Punk', 'RnB', 'Reggae', 'RocknRoll', 'Soul', 'Other', name='genre')
    genre.drop(op.get_bind())
    # ### end Alembic commands ###
